---
title: "Short_TloadDback"
author: "Sofie Raeymakers"
date: "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"
output: html_document
---


```{r setup, include=FALSE}
rm(list = ls()) # Clear environment
cat("\014") # Clear console
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
```
# A Data Analysis Report {.tabset}

```{r packages, include = FALSE}
##### Set environment #####

# Install packages
list.of.packages <- c('tidyverse', 'effects', 'emmeans', 'data.table', 'dplyr', 'lme4', 'ggplot2', 'MuMIn', 'effsize', 'reshape2','cowplot', 'car', 'ggpubr', 'rstatix', 'report') # All relevant packages
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])] # Check if any of these packages are not yet installed
if(length(new.packages)) install.packages(new.packages) # If any packages are not yet installed, install them
library(tidyverse)
library(effects)
library(emmeans)
library(data.table)
library(dplyr)
library(lme4)
library(ggplot2)
library(MuMIn)
library(effsize)
library(reshape2)
library(cowplot)
library(car)
library(ggpubr)
library(rstatix)
library(report)

# Get and declare functions
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
source("C:/Users/ASUSTeK/OneDrive/Documenten/Github/Short_TLoadDBack/functions.R") # file in the same directory for functions so they're together
#Set working directory to the folder in which all CSV files are located
Dir = "C:/Users/ASUSTeK/OneDrive/Documenten/Github/Short_TLoadDBack/Data/"
setwd(Dir)

# save figures
if (!dir.exists("figures")){ # Create folder for storing the figures if it doesn't exist yet
  dir.create("figures")}
plotPrefix <- paste0(Dir,"figures/") # Prefix to easily store figures later
```

Sofie Raeymakers


***

## Intro

explaination study

## Vigilance




### PVT Differences

```{r PVT_Differences, message=FALSE, warning = FALSE}
##########################################
  ### PVT/VIGILANCE/RT ###
#########################################

#Download PVT data (this datafile is made in 'preprocessing')
data <- read.csv(paste0(Dir, "PVT.csv"), header = TRUE, sep = )
data$RT <- 1/(data$RT/1000) # mean 1/RT

## CREATE DATAFRAME  with the MeanRT per ID, Day, Condition
PVT <- as.data.frame(group_by(data, Test, Day, Condition, ID) %>%
  summarise(
    count = n(),
    Mean = mean(RT, na.rm = TRUE)))
PVT <- PVT[!(PVT$ID==49),] # to make both conditions even amount of participants

# make factors
PVT$Day <- factor(PVT$Day)
PVT$ID <- factor(PVT$ID)
PVT$Condition <- factor(PVT$Condition)
names(PVT)[names(PVT)=="Test"] <- "Time"
PVT$Time <- as.factor(PVT$Time)

### CHECKING ASSUMPTIONS ####
# Time x Condition 2-way ANOVA with interaction effect (what Borrogan did)
model <- aov(Mean ~ Condition * Day * Time, data= PVT)
# HOMOGENEITY OF VARIANCE
plot(model, 1) # residuqls vs fits plot shows no evident relationship residuals and fitted values (means of groups)
leveneTest(Mean~ Day * Condition, data= PVT) # nono sign
# NORMALITY
aov_residuals <- residuals (object=model)
shapiro.test(x=aov_residuals) # sign, but OK: n>30
ggqqplot(PVT, "Mean", ggtheme = theme_bw()) +
  facet_grid(Day ~ Condition) # clearly not normal

# OUTLIERS
summary(PVT$Mean)
outliers <- boxplot(PVT$Mean, plot=FALSE)$out
# remove 
PVT<- PVT[-which(PVT$Mean %in% outliers),]# Result the SAME for data with or without outliers: because it is glmer
# but removing the outliers makes visualisations much more readable
d<-melt(data.frame(RT=c(PVT$Mean))) # we melt to wide format
distribution_plot (d, 'Mean') # much better
qqPlot(PVT$Mean) # much better


## ANALYSIS
three_w <- lm(Mean ~ Time*Condition*Day, data= PVT)
model <- aov(three_w)
summary(model)# non sign so no post-hoc tests
report(model)

emmeans1<- emmeans(three_w, pairwise ~ Time*Condition*Day, adjust ="fdr", type='response')
emmean_dataframe <- summary(emmeans1)$emmeans

sum <- sum_3 (PVT, 'Day', 'Condition', 'Time', 'Mean')

## VISUALISATION
# boxplot 
ggboxplot(
  PVT, x = "Condition", y = "Mean",
  color = "Time", palette = "jco",
  facet.by = "Day", short.panel.labs = FALSE)

## plot with error bars
pl <- plotty(PVT, emmean_dataframe, 'Time', 'Mean', 'Condition', 'emmean', 'Vigilance') +
 facet_grid(.~Day)+
 scale_x_discrete(labels=c("Before", "After"))
ggsave(pl, file=paste0(plotPrefix, "PVT_Plot.jpg"), width = 2500, height = 1500, dpi = 300, units = "px")
pl

```
--------------------------------------------------------------

## Subjective CF: VAS-f

= subjective measure of fatigue on 1-10 scale
we want to know if there is a difference in VAS before and after Test

```{r VASf, message=FALSE, warning = FALSE}
##########################################
  ### VAS-f: fatigue ###
#########################################

#### DOWNLOAD + CLEAN DATA ####
data <- read.csv(paste0(Dir, "VAS.csv"), header = TRUE, sep = )
data <-data[(grepl("quantised", data$Question.Key)),] #VAS has 'quantised: 1-11 instead of 0-10
# create dataframe
VAS <- as.data.frame(group_by(data, Test, Day, Condition, ID) %>%
  summarise(
    count = n(),
    Mean = mean(Response, na.rm = TRUE))) 

#factors
VAS$Day <- as.factor(VAS$Day)
VAS$Condition <- as.factor(VAS$Condition)
VAS$ID <- as.factor(VAS$ID)
names(VAS)[names(VAS)=="Test"] <- "Time"
VAS$Time <- as.factor(VAS$Time)

### CHECKING ASSUMPTIONS ####
# Time x Condition 2-way ANOVA with interaction effect (what Borrogan did)
model <- aov(Mean ~ Condition * Day, data= VAS)
summary(model)# no sign! this is good, means vigilance was same in all conditions
# HOMOGENEITY OF VARIANCE
leveneTest(Mean~ Time * Condition, data= VAS) # no homogeneity! problem! 
plot(model, 1) # residuqls vs fits plot shows no evident relationship residuals and fitted values (means of groups)
# NORMALITY
aov_residuals <- residuals (object=model)
shapiro.test(x=aov_residuals) #  
#visualisation
plot(model, 2) #normal
ggqqplot(VAS, "Mean", ggtheme = theme_bw()) +
  facet_grid(Day ~ Condition)#  very obviously NOT a normal distribution
# SPHERICITY: ok, bc all conditions 2 levels

#visualise
d<-melt(data.frame(VAS=c(VAS$Mean))) # we melt to wide format
distribution_plot (d, 'Mean')
qqPlot(VAS$Mean) 


#### repeated-measures ANOVA ####
three_w <- lm(Mean ~ Time*Condition*Day, data= VAS)
model <- aov(three_w)
summary(model)
report(model)

pw2<- VAS %>%
  group_by (Condition)%>%
  pairwise_t_test(Mean~Time, paired=TRUE,
                  p.adjust.method='bonferroni')
data.frame(pw2)

emmeans1<- emmeans(three_w, pairwise ~ Time*Condition*Day, adjust ="fdr", type = "response")
emmean_dataframe <- summary(emmeans1)$emmeans
emmeans1

sum <- sum_3 (VAS, 'Time', 'Condition', 'Day', 'Mean')

## VISUALISATION
# boxplot 
ggboxplot(
  VAS, x = "Condition", y = "Mean",
  color = "Time", palette = "jco",
  facet.by = "Day", short.panel.labs = FALSE)

## plot with error bars
max_y<-max(VAS$Mean)
pl <- plotty(VAS, emmean_dataframe, 'Time', 'Mean', 'Condition', 'emmean', 'VAS-f') +
 facet_grid(.~Day)+
scale_x_discrete(labels=c("Before", "After"))
ggsave(pl, file=paste0(plotPrefix, "VAS_Plot.jpg"), width = 2500, height = 1500, dpi = 300, units = "px")
pl

two_w <- lm(Mean ~ Time*Condition, data= VAS)
emmeans1<- emmeans(three_w, pairwise ~ Time*Condition, adjust ="fdr", type = "response")
emmean_dataframe <- summary(emmeans1)$emmeans
emmeans1

sum <- sum_2 (VAS, 'Time', 'Condition', 'Mean')
pl <- plotty(VAS, emmean_dataframe, 'Condition', 'Mean', 'Time', 'emmean', 'VAS-f')+
  scale_fill_manual(values = c("blue", 'red'), #colours used in plot
                    name='', labels= c('before', 'after'))
pl

```

-----------------------------------------------------------------------------------

## Objective CF

* We will test  the evolution of Performance (weighted accuracy) during TloadDback with Condition (HCL/LCL) and Time (t1-t3) as within-subject factors.
* interested in main effect e.g. t1>t4 and Condition x Time interaction on the Acc

```{r Performance, message=FALSE, warning = FALSE}
##########################################
  ### PERFORMANCE/ ACCURACY/ OBJECTIVE CF ###
#########################################

#### DOWNLOAD + CLEAN DATA ####
data<- read.csv(paste0(Dir, "EXP.csv"), header = TRUE, sep = )
# we remove rows that have prop_correct == NA , because these are lines in the data where the ERROR message was shown (accuracy=0)
data <- data[!is.na(data$prop_correct),]
# create a trial.index that goes from 1 to the number of trials:  not every participant has equal amount of trials, depends on their speed/accuracy
for (i in 1:97) { data$trial.index[data$ID==i]= 1:length(unique(data$Trial.Index[data$ID ==i]))}
# create var Time that indicates if it is part of t1, t2, t3. t1 is the first 40%, t2 middle 20%, t3 last 40% 
# we work with percentages because the #trials differs per ptt AND per day: 
for (i in 1:97) {
  data$Time[data$ID ==i & data$Day==1] = 2 # day 1
  data$Time[data$ID ==i & data$Day==1 & data$trial.index<(0.6* length(data$trial.index[data$Day==1 & data$ID==i])) ] = "middle"
  data$Time[data$ID ==i & data$Day==1 & data$trial.index<(0.4* length(data$trial.index[data$Day==1 & data$ID==i])) ] = 1
  data$Time[data$ID ==i & data$Day==2] = 2 # day 2
  data$Time[data$ID ==i & data$Day==2 & data$trial.index<(0.6* length(data$trial.index[data$Day==2 & data$ID==i])) ] = "middle"
  data$Time[data$ID ==i & data$Day==2 & data$trial.index<(0.4* length(data$trial.index[data$Day==2 & data$ID==i])) ] = 1
}
#remove 'middle'
data <- data[!(data$Time=="middle"),]
# CREATE DATAFRAME, with the Mean prop_correct per ID, Time, Day, Condition
EXP <- as.data.frame (group_by(data, Condition, Day, Time, ID) %>%
  summarise(
    count = n(),
    Mean = mean(prop_correct, na.rm = TRUE)))
 EXP <- EXP[!(EXP$ID==49),]

# set factors
EXP$Time <- as.factor(EXP$Time)
EXP$Condition <- as.factor(EXP$Condition)
EXP$Day <- as.factor(EXP$Day)
EXP$ID <- as.factor(EXP$ID)


### CHECKING ASSUMPTIONS ####
# Time x Condition 2-way ANOVA with interaction effect
model <- aov(Mean ~ Condition*Time, data= EXP)
## HOMOGENEITY OF VARIANCE
leveneTest(Mean~ Time * Condition, data= EXP) # no homogeneity! problem! 
box_m(EXP[, 'Mean', drop=FALSE], EXP$Condition) # no homogeneity of variance
plot(model, 1) # residuqls vs fits plot shows no evident relationship residuals and fitted values (means of groups)

## NORMALITY
aov_residuals <- residuals (object=model)
shapiro.test(x=aov_residuals) # no normality! 
ggqqplot(EXP, "Mean", ggtheme = theme_bw()) +
  facet_grid(Time ~ Condition)#  very obviously NOT a normal distribution

#visualise
d<-melt(data.frame(EXP=c(EXP$Mean))) # we melt to wide format
distribution_plot (d, 'Mean')


#### repeated-measures ANOVA ####
three_w <- lm(Mean ~ Time*Condition*Day, data= EXP)
model <- aov(three_w)
summary(model)
report(model)

sum_2(EXP, 'Time', 'Condition', 'Mean')
pw2<- EXP %>%
  group_by (Condition)%>%
  pairwise_t_test(Mean~Time, paired=TRUE,
                  p.adjust.method='bonferroni')
data.frame(pw2)

sum_2(EXP, 'Time', 'Day', 'Mean')
pw2<- EXP %>%
  group_by (Day)%>%
  pairwise_t_test(Mean~Time, paired=TRUE,
                  p.adjust.method='bonferroni')
data.frame(pw2)


emmeans1<- emmeans(three_w, pairwise ~ Time*Condition*Day, adjust ="fdr", type = "response")
emmean_dataframe <- summary(emmeans1)$emmeans
emmeans1

sum<- sum_3 (EXP, 'Time', 'Condition', 'Day', 'Mean')

## VISUALISATION
# boxplot 
ggboxplot(
  EXP, x = "Condition", y = "Mean",
  color = "Time", palette = "jco",
  facet.by = "Day", short.panel.labs = FALSE)

## plot with error bars
pl <- plotty(EXP, emmean_dataframe, 'Time', 'Mean', 'Condition', 'emmean', 'Performance') +
 facet_grid(.~Day)+
scale_x_discrete(labels=c("Before", "After"))
ggsave(pl, file=paste0(plotPrefix, "EXP_Plot.jpg"), width = 2500, height = 1500, dpi = 300, units = "px")
pl
```

## COMPONENTS
```{r Components, message=FALSE, warning = FALSE}
### COMPONENTS (Color/Pic)####

# evolution over time for 2 components of the task
# Pics: decide if big/small. Color: decide if same as DualBack: more Working Memory
EXP1 <- as.data.frame (group_by(data, Condition, Day, Time, ID, Stim) %>%
  summarise(
    count = n(),
    Mean = mean(prop_correct, na.rm = TRUE) ))
# set factors
EXP1$Time <- as.factor(EXP1$Time)
EXP1$Condition <- as.factor(EXP1$Condition)
EXP1$Day <- as.factor(EXP1$Day)
EXP1$ID <- as.factor(EXP1$ID)
EXP1$Stim <- as.factor(EXP1$Stim)

#### repeated-measures ANOVA ####
two_w <- lm(Mean ~ Time*Stim, data= EXP1)
model <- aov(two_w)
summary(model)
report(model)
three_w <- lm(Mean~Time * Stim * Condition, data=EXP1)
emmeans1<- emmeans(two_w, pairwise ~ Time*Stim, adjust ="fdr", type = "response")
emmean_dataframe <- summary(emmeans1)$emmeans
emmeans1

sum <- sum_2 (EXP1, 'Stim','Time', 'Mean')
sum

ggboxplot(
  EXP1, x = "Time", y = "Mean",
  color = "Stim", palette = "jco",
   short.panel.labs = FALSE)

pl <- plotty(EXP1, emmean_dataframe, 'Stim', 'Mean', 'Time', 'emmean', 'Components')+
  scale_fill_manual(values = c("blue", 'red'), #colours used in plot
                    name='', labels= c('before', 'after'))
ggsave(pl, file=paste0(plotPrefix, "EXP_Plot.jpg"), width = 2500, height = 1500, dpi = 300, units = "px")
pl
```


-----------------------------------------------------------------------------------

## CORRELATIONS

```{r message=FALSE, warning = FALSE}
##########################################
  ### CORRELATIONS ###
#########################################C
 
 names(VAS)[names(VAS)=="Mean"] <- "VASf"
 names(EXP)[names(EXP)=="Mean"] <- "Acc"

 ### VAS-f ###

 ## CORR VAS-f Mean score between Day 1 and Day 2 (test-retest reliability)
 # HCL
 Day1 <- VAS$VASf[VAS$Day==1 & VAS$Condition=='HCL']
 Day2 <- VAS$VASf[VAS$Day==2 & VAS$Condition=='HCL']
 VASfHCL <- corrplot(Day1, Day2, 'Day1', 'Day2') +ggtitle('VASf HCL')
 #LCL
 Day1 <- VAS$VASf[VAS$Day==1 & VAS$Condition=='LCL']
 Day2 <- VAS$VASf[VAS$Day==2 & VAS$Condition=='LCL']
 VASfLCL <- corrplot(Day1, Day2, 'Day1', 'Day2') +ggtitle('VASf LCL')
 # cor.test(VAS$VASf[VAS$Condition=='HCL'], VAS$VASf[VAS$Condition=='LCL'],  method="spearman")# not Pearson because: not normal distribution
 # cor.test(VAS$Mean[VAS$Condition=='HCL'], VAS$Mean[VAS$Condition=='LCL'],  method="kendall")

 ## CORR VAS-f delta between Day 1 and Day 2
 #HCL
 Day1 <- VAS$VASf[VAS$Day==1 & VAS$Condition=='HCL' & VAS$Time==2]- VAS$VASf[VAS$Day==1 & VAS$Condition=='HCL' & VAS$Time==1]
 Day2 <- VAS$VASf[VAS$Day==2 & VAS$Condition=='HCL' & VAS$Time==2]- VAS$VASf[VAS$Day==2 & VAS$Condition=='HCL' & VAS$Time==1]
 VASf_delta_HCL <- corrplot(Day1, Day2, 'Day1', 'Day2') +ggtitle('VASf delta HCL')
 #LCL
 Day1 <- VAS$VASf[VAS$Day==1 & VAS$Condition=='LCL' & VAS$Time==2]- VAS$VASf[VAS$Day==1 & VAS$Condition=='LCL' & VAS$Time==1]
 Day2 <- VAS$VASf[VAS$Day==2 & VAS$Condition=='LCL' & VAS$Time==2]- VAS$VASf[VAS$Day==2 & VAS$Condition=='LCL' & VAS$Time==1]
 VASf_delta_LCL <- corrplot(Day1, Day2, 'Day1', 'Day2') +ggtitle('VASf delta LCL')

 VASfCORR <- ggarrange(VASfHCL, VASfLCL, VASf_delta_HCL, VASf_delta_LCL + rremove("x.text"),
           labels = c("A", "B", "C", "D"),
           ncol = 2, nrow = 2)
 ggsave(VASfCORR, file=paste0(plotPrefix, "VASf_CORR.jpg"), width = 2500, height = 1500, dpi = 300, units = "px")
 VASfCORR

 ### Accuracy ###

 ## CORR Accuracy Day 1 and Day 2  (test-retest reliability)
 #HCL
 Day1 <- EXP$Acc[EXP$Day==1 & EXP$Condition=='HCL' & EXP$Time==2]- EXP$Acc[EXP$Day==1 & EXP$Condition=='HCL' & EXP$Time==1]
 Day2 <- EXP$Acc[EXP$Day==2 & EXP$Condition=='HCL' & EXP$Time==2]- EXP$Acc[EXP$Day==2 & EXP$Condition=='HCL' & EXP$Time==1]
 EXPHCL<-corrplot(Day1, Day2, 'Day1', 'Day2') +ggtitle('Performance HCL')
 #LCL
 Day1 <- EXP$Acc[EXP$Day==1 & EXP$Condition=='LCL' & EXP$Time==2]- EXP$Acc[EXP$Day==1 & EXP$Condition=='LCL' & EXP$Time==1]
 Day2 <- EXP$Acc[EXP$Day==2 & EXP$Condition=='LCL' & EXP$Time==2]- EXP$Acc[EXP$Day==2 & EXP$Condition=='LCL' & EXP$Time==1]
 EXPLCL<-corrplot(Day1, Day2, 'Day1', 'Day2') +ggtitle('Performance LCL')

 ## CORR Accuracy delta between Day 1 and Day 2
 #HCL
 Day1 <- EXP$Acc[EXP$Day==1 & EXP$Condition=='HCL' & EXP$Time==2]- EXP$Acc[EXP$Day==1 & EXP$Condition=='HCL' & EXP$Time==1]
 Day2 <- EXP$Acc[EXP$Day==2 & EXP$Condition=='HCL' & EXP$Time==2]- EXP$Acc[EXP$Day==2 & EXP$Condition=='HCL' & EXP$Time==1]
 EXP_DELTA_HCL<- corrplot(Day1, Day2, 'Day1', 'Day2') +ggtitle('Performance delta HCL') # negative correlation: when high in day 1, low in day 2
 #LCL
 Day1 <- EXP$Acc[EXP$Day==1 & EXP$Condition=='LCL' & EXP$Time==2]- EXP$Acc[EXP$Day==1 & EXP$Condition=='LCL' & EXP$Time==1]
 Day2 <- EXP$Acc[EXP$Day==2 & EXP$Condition=='LCL' & EXP$Time==2]- EXP$Acc[EXP$Day==2 & EXP$Condition=='LCL' & EXP$Time==1]
 EXP_DELTA_LCL<-corrplot(Day1, Day2, 'Day1', 'Day2') +ggtitle('Performance delta LCL') # positive correlation: when high in day 1, high in day 2

 EXPCORR <- ggarrange(EXPHCL, EXPLCL, EXP_DELTA_HCL, EXP_DELTA_LCL + rremove("x.text"),
           labels = c("A", "B", "C", "D"),
           ncol = 2, nrow = 2)
 ggsave(EXPCORR, file=paste0(plotPrefix, "EXP_CORR.jpg"), width = 2500, height = 1500, dpi = 300, units = "px")
 EXPCORR

  # Create 1 big dataframe
  df <- merge(VAS, EXP, by = c('Day','Time', 'Condition', 'ID'))

 length(unique(df$ID[df$Condition=='HCL']))
 length(unique(df$ID[df$Condition=='LCL']))

 
#HCL
 VAS_f <- df$Mean[df$Time==2 & df$Condition=='HCL' & df$Day==1] - df$Mean[df$Time==1 & df$Condition=='HCL' & df$Day==1]
 ACC<- df$Acc[df$Time==2 & df$Condition=='HCL' & df$Day==1] - df$Acc[df$Time==1 & df$Condition=='HCL' & df$Day==1]
 DELTAHCL_1<- corrplot(VAS_f, ACC, 'VASf delta', 'Performance delta') +ggtitle('delta correlations HCL Day 1') # no correlation: change before-after test in VASf no correlation with obj CF changes
 #LCL
 VAS_f <- df$Mean[df$Time==2 & df$Condition=='LCL' & df$Day==1] - df$Mean[df$Time==1 & df$Condition=='LCL' & df$Day==1]
 ACC<- df$Acc[df$Time==2 & df$Condition=='LCL' & df$Day==1] - df$Acc[df$Time==1 & df$Condition=='LCL' & df$Day==1]
 DELTALCL_1<- corrplot(VAS_f, ACC, 'VASf delta', 'Performance delta') +ggtitle('delta correlations LCL Day 1')
 
  VAS_f <- df$Mean[df$Time==2 & df$Condition=='HCL' & df$Day==2] - df$Mean[df$Time==1 & df$Condition=='HCL' & df$Day==2]
 ACC<- df$Acc[df$Time==2 & df$Condition=='HCL' & df$Day==2] - df$Acc[df$Time==1 & df$Condition=='HCL' & df$Day==2]
 DELTAHCL_2<- corrplot(VAS_f, ACC, 'VASf delta', 'Performance delta') +ggtitle('delta correlations HCL Day 2') # no correlation: change before-after test in VASf no correlation with obj CF changes
 #LCL
 VAS_f <- df$Mean[df$Time==2 & df$Condition=='LCL' & df$Day==2] - df$Mean[df$Time==1 & df$Condition=='LCL' & df$Day==2]
 ACC<- df$Acc[df$Time==2 & df$Condition=='LCL' & df$Day==2] - df$Acc[df$Time==1 & df$Condition=='LCL' & df$Day==2]
 DELTALCL_2<- corrplot(VAS_f, ACC, 'VASf delta', 'Performance delta') +ggtitle('delta correlations LCL Day 2')
 
DELTACORR <- ggarrange(DELTAHCL_1, DELTALCL_1, DELTAHCL_2, DELTALCL_2 + rremove("x.text"),
           labels = c("A", "B", "C", "D"),
           ncol = 2, nrow = 2)
 ggsave(DELTACORR, file=paste0(plotPrefix, "DELTACORR.jpg"), width = 2500, height = 1500, dpi = 300, units = "px")
 DELTACORR 
 
```


