---
title: "EXP_ANALYSIS"
author: "Sofie Raeymakers"
date: "7/1/2022"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls()) # Clear environment
cat("\014") # Clear console
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning = FALSE}
##### Set environment #####

library(tidyverse)
library(effects)
library(emmeans)
library(rstatix)
library(data.table)
library(dplyr)
library(ggplot2)
library(MuMIn)
library(effsize)
library(reshape2)
library(cowplot)
library(car)
library(ggpubr)
library(lme4)

# Get and declare functions
#Set working directory to the folder in which all CSV files are located

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
source("C:/Users/ASUSTeK/OneDrive/Documenten/Github/Short_TLoadDBack/functions.R") # This is a file in the same directory where you can stash your functions so you can save them there and have them together

Dir = "C:/Users/ASUSTeK/OneDrive/Documenten/Github/Short_TLoadDBack/Data/"
setwd(Dir)
#Download EXP data
data<- read.csv(paste0(Dir, "EXP.csv"), header = TRUE, sep = )

```


```{r}
##### OBJECTIVE CF in the TloadDback task ##### 
#we compute the evolution of performance during TloadDback
# weighted accuracy (prop_correct): t1 and t2 is first and second 20%, t4 and t5 last 20% (with 20% in middle)

#we remove rows that have prop_correct == NA '
#because these are lines in the data where the ERROR message was shown (accuracy=0)
data <- data[!is.na(data$prop_correct),]

# create a trial.index that goes from 1 to the number of trials
# not every participant has equal amount of trials, because dependent on their speed/accuracy
for (i in 1:97) {
  data$trial.index[data$ID==i]= 1:length(unique(data$Trial.Index[data$ID ==i]))
}
length(data$trial.index[is.na(data$trial.index)]) # check number of NA's, should be 0

#remove some unnecessary columns
data = subset(data, select = -c(Local.Date, Participant.Private.ID, Task.Name, Accuracy_Level, Time.Elapsed, Trial.Index))

# create var Time that indicates if it is part of t1, t2, t3, t4 or t5
# we need to work with percents because the #trials differs per ptt 
length(unique(data$trial.index[data$ID ==1])) #This is the highest amount of trials on either day 
count_index <- data %>% count(ID)
count_index$n[count_index$ID==1] #total amount of trials for this participant (day 1 + day 2)

# amount of trials differ depending on the day, so calculate per day!
# each t has 20%, with 20% empty in the middle (t3)
for (i in 1:97) {
  data$Time[data$ID ==i & data$Day==1] = "t3" # day 1
  # data$Time[data$ID ==i & data$Day==1 & data$trial.index<(0.8* length(data$trial.index[data$Day==1 & data$ID==i])) ] = "t4" # less than 80% of the numver of trials on day 1 for that ppt
  data$Time[data$ID ==i & data$Day==1 & data$trial.index<(0.6* length(data$trial.index[data$Day==1 & data$ID==i])) ] = "t2"
  data$Time[data$ID ==i & data$Day==1 & data$trial.index<(0.4* length(data$trial.index[data$Day==1 & data$ID==i])) ] = "t1"
  # data$Time[data$ID ==i & data$Day==1 & data$trial.index<(0.2* length(data$trial.index[data$Day==1 & data$ID==i])) ] = "t1"
   
  data$Time[data$ID ==i & data$Day==2] = "t3" # day 2
  # data$Time[data$ID ==i & data$Day==2 & data$trial.index<(0.8* length(data$trial.index[data$Day==2 & data$ID==i])) ] = "t4"
  data$Time[data$ID ==i & data$Day==2 & data$trial.index<(0.6* length(data$trial.index[data$Day==2 & data$ID==i])) ] = "t2"
  data$Time[data$ID ==i & data$Day==2 & data$trial.index<(0.4* length(data$trial.index[data$Day==2 & data$ID==i])) ] = "t1"
  # data$Time[data$ID ==i & data$Day==2 & data$trial.index<(0.2* length(data$trial.index[data$Day==2 & data$ID==i])) ] = "t1"
}

length(data$Time[is.na(data$Time)]) #N1s, should be 0

```

```{r}
######## mixed- design ANOVA computed on weighted accuracy scores (prop_correct/Acc) with Condition (HCL/LCL) and Time (t1, t2 etc) as within-subject factors. 
# We look at main effect e.g. t1>t4 and Condition x Time interaction on the Acc


#### CREATE DATAFRAME ####
# with the Acc prop_correct per ID, Time, Day, Condition
EXP <- group_by(data, Condition, Day, Time, ID) %>%
  summarise(
    count = n(),
    Acc = mean(prop_correct, na.rm = TRUE)
  )
EXP <- as.data.frame(EXP)
head(EXP) # mean Acc (prop_correct) per ID, Time, Day and Condition

# set factors
EXP$Day <- as.factor(EXP$Day)
EXP$Time <- as.factor(EXP$Time)
EXP$Condition <- as.factor(EXP$Condition)
EXP$ID <- as.factor(EXP$ID)


### CHECKING ASSUMPTIONS ####
### Time x Condition 2-way ANOVA with interaction effect
res.aov2 <- aov(Acc ~ Condition*Time, data= EXP)
summary(res.aov2)

## HOMOGENEITY OF VARIANCE
plot(res.aov2, 1) # residuqls vs fits plot shows no evident relationship residuals and fitted values (means of groups)
#Levene's test homogeneity variances
leveneTest(Acc~ Time * Condition, data= EXP) # no homogeneity! problem! 
box_m(EXP[, 'Acc', drop=FALSE], EXP$Condition) # no homogeneity of variance

## NORMALITY
plot(res.aov2, 2)
aov_residuals <- residuals (object=res.aov2)
shapiro.test(x=aov_residuals) # no normality! 

EXP %>%
  group_by(Condition, Time) %>%
  shapiro_test(Acc) # no normal distribution!

ggqqplot(EXP, "Acc", ggtheme = theme_bw()) +
  facet_grid(Time ~ Condition)
ggqqplot(EXP, "Acc", ggtheme = theme_bw()) +
  facet_grid( ~Condition) #  very obviously NOT a normal distribution
#boxplot visualisation
bxp <- ggboxplot(
  EXP, x = "Condition", y = "Acc", palette = "jco")
bxp
# boxplot visualisation
bxp <- ggboxplot(
  EXP, x = "Time", y = "Acc",
  color = "Condition", palette = "jco")
bxp


## SPHERICITY: Mauchly's test
x<-anova_test(data=EXP, dv= Acc, wid= ID, between= Condition, within= c(Time, Day))
get_anova_table(x, correction = c('GG')) #variances are NOT equal! 
x$'Sphericity Corrections'

## OUTLIERS
EXP %>%
  group_by(Condition, Time) %>%
  identify_outliers(Acc)
 outliers <- boxplot(EXP$prop_correct, plot=FALSE)$out
summary(EXP$Acc)
outliers <- boxplot(EXP$Acc, plot=FALSE)$out
#remove outliers
#remove under 3? (sign not paying attention? a bit arbitrary)
#EXP <-  EXP[!EXP$Acc<0.3,]
list_quantiles <- tapply(EXP$Acc, EXP$Condition, quantile)
Q1s <- sapply(1:2, function(i) list_quantiles[[i]][2])
Q3s <- sapply(1:2, function(i) list_quantiles[[i]][4])
IQRs <- tapply(EXP$Acc, EXP$Condition, IQR)
Lowers <- Q1s - 1.5*IQRs
Uppers <- Q3s + 1.5*IQRs
datas <- split(EXP, EXP$Condition)
data_no_outlier <- NULL
for (i in 1:2){
out <- subset(datas[[i]], datas[[i]]$Acc > Lowers[i] & datas[[i]]$Acc < Uppers[i])
data_no_outlier <- rbind(data_no_outlier, out)
}
EXP<- as.data.frame(data_no_outlier)


#### STATISTICAL TEST ####

## CONDITION * TIME 

#unbalanced design! not equal amount in each group
length(unique(EXP$ID[EXP$Condition=='LCL']))
length(unique(EXP$ID[EXP$Condition=='HCL']))

#even after log transform and removing outliers we have clearly not a normal distribution 
# so we need to use GLM. Anova because unbalanced design: not equal amount ppt in each group. 
#https://stats.stackexchange.com/questions/189115/fitting-a-binomial-glmm-glmer-to-a-response-variable-that-is-a-proportion-or-f
#BINOMIAL 

#The outcome (accuracy) is between 0 and 1, continuous and non-negative: proportion so BINOMIAL 
#we need to use weights argument for the #trials that lead to the proportion of Acc
two_w <- glmer(Acc ~ Condition * Time + (1 | ID), weights = count,
   family = binomial, data = EXP)
emmeans1<- emmeans(two_w, pairwise ~ Condition * Time, adjust ="fdr", type = "response")
emmean_dataframe <- summary(emmeans1)$emmeans

Anova(two_w, type='III')
summary(emmeans1)
  
my_sum <- EXP %>%
  group_by(Time, Condition) %>%
  summarise(
    n = n(), 
    mean = mean(Acc),
    sd = sd(Acc)
  ) %>%
  mutate( se = sd/sqrt(n)) %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
my_sum

emmean_dataframe$n = my_sum$n
emmean_dataframe$ic = my_sum$ic

## Visualisation Condition * Time 
pl<- ggplot()+
    geom_flat_violin(data= EXP, aes(x= Time, y= Acc, fill=Condition),position = position_nudge(x =.2, y = 0), alpha=.5, adjust = 1.5, colour = NA)+
  geom_boxplot(data= EXP, aes(x = Time, y = Acc, fill = Condition), outlier.shape=NA, alpha= .45, width = .1, colour = "black") +
   geom_point(data= emmean_dataframe, aes(x =Time, y = prob, fill=Condition), position= position_dodge(0.1), size=4)+
  geom_errorbar( data= emmean_dataframe, aes(x=Time, ymin=prob-SE, ymax=prob+SE), width=0.05, colour="black", alpha=0.9, size=0.05) + #SD error bar 
  geom_errorbar(data= emmean_dataframe, aes(x=Time, ymin=prob-ic, ymax=prob+ic), width=0.4, colour="red", alpha=0.9, size=0.05) + #C.I.
    theme(
      legend.key.size=unit(1.3, 'cm'),
      legend.text=element_text(size=13),
      plot.title = element_text(size=rel(2)),
      panel.border = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(colour = "black"),
      panel.grid.major.y = element_line( size=.1, color="#dedede" ),
      axis.text.x=element_text(size=rel(1.5)),
      axis.title.y=element_text(size=rel(1.4)),
      axis.title.x = element_blank())
pl # Acc is higher in LCL at each time point
emmean_dataframe 


## Visualisation of just Condition
one_w <- glmer(Acc ~ Condition  + (1 | ID), weights = count,
   family = binomial, data = EXP)
emmeans1<- emmeans(one_w, pairwise ~ Condition, adjust ="fdr", type = "response")
emmean_dataframe <- summary(emmeans1)$emmeans

Anova(one_w, type='III')
summary(emmeans1)

pl<- ggplot(EXP, aes(x= Condition, y = Acc))+
    geom_flat_violin(aes(fill=Condition),position = position_nudge(x =.2, y = 0), alpha=.5, adjust = 1.5, colour = NA)+
  geom_boxplot(aes(x = Condition, y = Acc, fill = Condition), outlier.shape=NA, alpha= .45, width = .1, colour = "black") +
   geom_point(data= emmean_dataframe, aes(x =Condition, y = prob, fill=Condition), position= position_dodge(0.1), size=4)+
    theme(
      legend.key.size=unit(1.3, 'cm'),
      legend.text=element_text(size=13),
      plot.title = element_text(size=rel(2)),
      panel.border = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(colour = "black"),
      panel.grid.major.y = element_line( size=.1, color="#dedede" ),
      axis.text.x=element_text(size=rel(1.5)),
      axis.title.y=element_text(size=rel(1.4)),
      axis.title.x = element_blank())
pl
emmean_dataframe# LCL clearly has higher Acc: 0.89 for LCL and 0.62 for HCL


#### COMPARE DAY 1 to DAY 2 #####

# Condition * Day: Day perhaps interesting 
two_w <- glmer(Acc ~ Condition * Day + (1 | ID), weights = count,
   family = binomial, data = EXP)
emmeans1<- emmeans(two_w, pairwise ~ Condition * Day, adjust ="fdr", type = "response")
emmean_dataframe <- summary(emmeans1)$emmeans

Anova(two_w, type='III')
summary(emmeans1)
  
my_sum <- EXP %>%
  group_by(Day, Condition) %>%
  summarise(
    n = n(), 
    mean = mean(Acc),
    sd = sd(Acc)
  ) %>%
  mutate( se = sd/sqrt(n)) %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
my_sum

emmean_dataframe$n = my_sum$n
emmean_dataframe$ic = my_sum$ic

## Visualisation Condition * Time 
pl<- ggplot()+
    geom_flat_violin(data= EXP, aes(x= Day, y= Acc, fill=Condition),position = position_nudge(x =.2, y = 0), alpha=.5, adjust = 1.5, colour = NA)+
  geom_boxplot(data= EXP, aes(x = Day, y = Acc, fill = Condition), outlier.shape=NA, alpha= .45, width = .1, colour = "black") +
   geom_point(data= emmean_dataframe, aes(x =Day, y = prob, fill=Condition), position= position_dodge(0.1), size=4)+
  geom_errorbar( data= emmean_dataframe, aes(x=Day, ymin=prob-SE, ymax=prob+SE), width=0.05, colour="black", alpha=0.9, size=0.05) + #SD error bar 
  geom_errorbar(data= emmean_dataframe, aes(x=Day, ymin=prob-ic, ymax=prob+ic), width=0.4, colour="red", alpha=0.9, size=0.05) + #C.I.
    theme(
      legend.key.size=unit(1.3, 'cm'),
      legend.text=element_text(size=13),
      plot.title = element_text(size=rel(2)),
      panel.border = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(colour = "black"),
      panel.grid.major.y = element_line( size=.1, color="#dedede" ),
      axis.text.x=element_text(size=rel(1.5)),
      axis.title.y=element_text(size=rel(1.4)),
      axis.title.x = element_blank())
pl # Acc is higher in day 2 for both conditions! 
emmean_dataframe 

```

```{r}

###### components (color/pic): mixed-D ANOVA Stim * Condition * Time ####
# assess seperately evoluiton within time for 2 components of the task: pics are big/small with  no WM component whereas balss have 8 different colors + n-back. which one is harder? We made a weighted accuracy where  
# mixed-design ANOVA with component (ball vs pic) and condition (HCL/LCL) and Time (t1-4) as within-subj factors. 
# interaction and main effect
# to indicate higher complexity WMM component (pics) compared to balls 

EXP <- group_by(data, Condition, Time, ID, Stim) %>%
  summarise(
    count = n(),
    Acc = mean(accuracy, na.rm = TRUE)
  )
EXP <- as.data.frame(EXP)
head(EXP)

# set factors
EXP$Time <- as.factor(EXP$Time)
EXP$Condition <- as.factor(EXP$Condition)
EXP$ID <- as.factor(EXP$ID)
EXP$Stim <- as.factor(EXP$Stim)

two_w <- glmer(Acc ~ Condition * Time * Stim + (1 | ID), weights = count,
   family = binomial, data = EXP)
emmeans1<- emmeans(two_w, pairwise ~ Condition * Time * Stim, adjust ="fdr", type = "response")
emmean_dataframe <- summary(emmeans1)$emmeans

Anova(two_w, type='III')
summary(emmeans1)

my_sum <- EXP %>%
  group_by(Time, Stim, Condition) %>%
  summarise(
    n = n(), 
    mean = mean(Acc),
    sd = sd(Acc)
  ) %>%
  mutate( se = sd/sqrt(n)) %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
my_sum

emmean_dataframe$n = my_sum$n
emmean_dataframe$ic = my_sum$ic


## CORR Acc score between two conditions (HCL and LCL)

```

