---
title: "PVT_VAS-f_analysis"
author: "Sofie Raeymakers"
date: "5/3/2022"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls()) # Clear environment
cat("\014") # Clear console
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning = FALSE}
##### Set environment #####

library(tidyverse)
library(effects)
library(emmeans)
library(data.table)
library(dplyr)
library(ggplot2)
library(MuMIn)
library(effsize)

# Get and declare functions
#Set working directory to the folder in which all CSV files are located

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
source("C:/Users/ASUSTeK/OneDrive/Documenten/Github/Short_TLoadDBack/functions.R") # This is a file in the same directory where you can stash your functions so you can save them there and have them together

Dir = "C:/Users/ASUSTeK/OneDrive/Documenten/Github/Short_TLoadDBack/Data/"
setwd(Dir)

#Download PVT data (this datafile is made in 'preprocessing')
PVT <- read.csv(paste0(Dir, "PVT.csv"), header = TRUE, sep = )

#Download VAS-f data
VAS <- read.csv(paste0(Dir, "VAS.csv"), header = TRUE, sep = )
#VAS has 'quantised: 1-11 instead of 0-10

#Download EXP data
EXP <- read.csv(paste0(Dir, "EXP.csv"), header = TRUE, sep = )

```

```{r}
### CHECKING TLOADNBACK#

#### EXP DAY 1/2 ####
EXP <- EXP[!(EXP$Day==1),]

# count 'accuracy' (0 or 1) in LCL vs HCL
sum(EXP$accuracy[EXP$Condition=="HCL"])
sum(EXP$accuracy[EXP$Condition=="LCL"])
mean(EXP$accuracy[EXP$Condition=="HCL"])
mean(EXP$accuracy[EXP$Condition=="LCL"])

EXP$Day <- as.factor(EXP$Day)
EXP$Condition <- as.factor(EXP$Condition)
EXP$ID <- as.factor(EXP$ID)

#do this with shihny!!
three_way_acc <-lm(accuracy~Condition * Day, data=EXP)
one_way_acc <- lm(accuracy~Condition , data=EXP)
summary(three_way_acc)
summary(one_way_acc)

three_way_prop <- lm(prop_correct~Condition * Day, data=EXP)
one_way_prop <- lm(prop_correct~Condition, data=EXP)
summary(three_way_prop)
summary(one_way_prop)


#visualise
emmeans1 <- emmeans(fit, pairwise ~ Condition | Day, adjust ="fdr", type = "response")
two_way_emm <- summary(emmeans1)$emmeans

emmeans2 <- emmeans(fit, pairwise ~ Condition, adjust ="fdr", type = "response")
one_way_emm <- summary(emmeans2)$emmeans

  
plot <- one_way_plotf(EXP, one_way_emm, "prop_correct")

plot <- two_way_plotf(EXP, two_way_emm, "prop_correct")




```

```{r}
#### CLEANING PVT ####

#Dataframe from day 1
PVT1 <- PVT[!(PVT$Day==2),]

library(reshape2)
library(cowplot)

#plot reaction times with raincloudplot
d<-melt(data.frame(rt=c(PVT1$RT))) # we melt to wide format 
ggplot(d, aes(x = variable, y = value, fill=variable))+
  geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust =2)+
  ylab('rt')+xlab('amount')+coord_flip()+theme_cowplot()+
  geom_point(position=position_jitter(width=.15), size=2)+
  geom_boxplot(width= .10, outlier.shape = NA)+
  theme(legend.position="none")+
  ggtitle("reaction times with outliers")

summary(PVT1$RT)
hist(PVT1$RT,
     xlab = "RT",
     main = "Histogram of RT",
     breaks = sqrt(nrow(PVT1)))

print('upper 97.5% bound')
quantile (PVT1$RT, 0.975)


# remove RT over 2000 millisec
PVT1 <- subset(PVT1, RT < 3800)
d<-melt(data.frame(rt=c(PVT1$RT)))
ggplot(d, aes(x = variable, y = value, fill=variable))+
  geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust =2)+
  geom_point(position=position_jitter(width=.15), size=0.25)+
  ylab('rt')+xlab('amount')+coord_flip()+theme_cowplot()+
  geom_boxplot(width= .10, outlier.shape = NA)+
  theme(legend.position="none")+
  guides(fill=FALSE)+
  ggtitle("reaction times < 3800 millisec")

summary(PVT1$RT)
hist(PVT1$RT,
     xlab = "RT",
     main = "Histogram of RT",
     breaks = sqrt(nrow(PVT1)))


out<-boxplot.stats(PVT1$RT)$out#outliers
out_ind<-which(PVT1$RT %in% c(out))#row numbers that contain outliers
boxplot(PVT1$RT, ylab='rt') #boxplot
mtext(paste('boxplot with outliers')) #boxplot with outliers

#remove outliers: sign that they were not paying attention
outliers <- boxplot(PVT1$RT, plot=FALSE)$out
PVT1<- PVT1[-which(PVT1$RT %in% outliers),]

# check normality of PVT1 RT
library("car")
qqPlot(PVT1$RT)

# log transform data
PVT1$RT = log(PVT1$RT)

qqPlot(PVT1$RT)


################ PVT ################

#plot reaction times with raincloudplot
library(reshape2)
library(cowplot)
d<-melt(data.frame(RT=c(PVT$RT))) # we melt to wide format 
ggplot(d, aes(x = variable, y = value, fill=variable))+
  geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust =2)+
  coord_flip()+
  theme_cowplot()+
  geom_point(position=position_jitter(width=.15), size=2)+
  geom_boxplot(width= .10, outlier.shape = NA)+
  theme(legend.position="none")


### Do like Borrogan : mean 1/RT

PVT$RT <- 1/(PVT$RT/1000) #1/RT

d<-melt(data.frame(RT=c(PVT$RT))) # we melt to wide format 
ggplot(d, aes(x = variable, y = value, fill=variable))+
  geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust =2)+
  coord_flip()+
  theme_cowplot()+
  geom_point(position=position_jitter(width=.15), size=2)+
  geom_boxplot(width= .10, outlier.shape = NA)+
  theme(legend.position="none")

# we have 97 iDs. Each participant is in either LCL or HCL
for (i in 1:97) {
  PVT$MeanRT[PVT$ID==i & PVT$Test==1 & PVT$Day==1]= mean (PVT$RT[PVT$ID==i & PVT$Test==1 & PVT$Day==1])
  PVT$MeanRT[PVT$ID==i & PVT$Test==2 & PVT$Day==1]= mean (PVT$RT[PVT$ID==i & PVT$Test==2 & PVT$Day==1])
  PVT$MeanRT[PVT$ID==i & PVT$Test==1 & PVT$Day==2]= mean (PVT$RT[PVT$ID==i & PVT$Test==1 & PVT$Day==2])
  PVT$MeanRT[PVT$ID==i & PVT$Test==2 & PVT$Day==2]= mean (PVT$RT[PVT$ID==i & PVT$Test==2 & PVT$Day==2])
  }

# remove duplicates: now only 1 datapoint per MeanRT
PVT_c <- PVT[!duplicated(PVT$MeanRT), ]

length(unique(PVT_c$MeanRT))
#388
97*4

glimpse(PVT_clean)





#plot reaction times with raincloudplot
d<-melt(data.frame(rt=c(PVT_c$MeanRT))) # we melt to wide format 
ggplot(d, aes(x = variable, y = value, fill=variable))+
  geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust =2)+
  ylab('MeanRT')+xlab('amount')+coord_flip()+theme_cowplot()+
  geom_point(position=position_jitter(width=.15), size=2)+
  geom_boxplot(width= .10, outlier.shape = NA)+
  theme(legend.position="none")+
  ggtitle("reciprocal reaction times")

summary(PVT_c$MeanRT)
hist(PVT_c$MeanRT,
     xlab = "MeanRT",
     main = "Histogram of MeanRT",
     breaks = sqrt(nrow(PVT)))

qqPlot(PVT_c$MeanRT)


```

```{r}

# make factors
PVT_c$Day <- factor(PVT_c$Day)
PVT_c$Test <- factor(PVT_c$Test)
PVT_c$Condition <- factor(PVT_c$Condition)

levels(PVT_c$Condition)

# formula <- lm( PVT_c$MeanRT ~ PVT_c$Condition * PVT_c$Day * PVT_c$Test + 1|PVT_c$ID)

# summarize data per group
library(dplyr)
sum <- group_by(PVT_c, Condition, Test, Day) %>%
  summarise(
    count = n(),
    mean = mean(MeanRT, na.rm = TRUE),
    sd = sd(RT, na.rm = TRUE)
  )
sum 



library(ggplot2)
ggplot(sum, aes(x=Condition, y=mean)) + 
  geom_violin()
ggplot(PVT_c, aes(x=Condition, y=MeanRT)) + 
  geom_violin()

library("ggpubr")
ggboxplot(PVT_c, x = "Condition", y = "MeanRT", 
          color = "Condition", palette = c("#00AFBB", "#E7B800", "#FC4E07"),
          ylab = "RT", xlab = "Condition")



# one_way <- lm(Diff~Condition , data=VASC)
# emmeans1 <- emmeans(one_way, pairwise ~ Condition, adjust ="fdr", type = "response")
# one_way_emm <- summary(emmeans2)$emmeans
# one_way_plotf(VASC, one_way_emm, "Diff")
# 
# Anova(one_way, type='III')
# summary(emmeans1)
# emmeans1$contrasts
# 
# two_way <-lm(Diff~Condition * Day, data=VASC)
# emmeans2 <- emmeans(one_way, pairwise ~ Condition, adjust ="fdr", type = "response")
# one_way_emm <- summary(emmeans2)$emmeans
# two_way_plotf(VASC, two_way_emm, "MeanR")
# 
# Anova(two_way, type='III')
# summary(emmeans2)
# emmeans2$contrasts


```

```{r}

########## VAS-f  DAY 1###########

#Dataframe from day 1
VAS1 <- VAS[!(VAS$Day==2),]
VAS1 = subset(VAS1, select = -c(Local.Date, Participant.Private.ID, Task.Name))

# take means
#each time 13 questions, with answers on a scale of 0-9 (Response)
# if Question.key contains 'quantised' then it is on 1-10 
VAS1 <-VAS1[(grepl("quantised", VAS1$Question.Key)),]

# take sum of the scale per participant, per day/test. 
for (i in 1:97) {
  VAS1$Sum[VAS1$ID==i & VAS1$Test==1 & VAS1$Day==1]= sum (VAS1$Response[VAS1$ID==i & VAS1$Test==1 & VAS1$Day==1])
  VAS1$Sum[VAS1$ID==i & VAS1$Test==2 & VAS1$Day==1]= sum (VAS1$Response[VAS1$ID==i & VAS1$Test==2 & VAS1$Day==1])
}

# check if conditions are equal
length(VAS1$Sum[VAS1$Test==1 & VAS1$Day ==1 & VAS1$ID==1])
length(VAS1$Sum[VAS1$Test==2 & VAS1$Day ==1 & VAS1$ID==1])

# correcting for baseline: VAS1C$Diff as VAS1 op test 2 - test 1 per dag
for (i in 1:97) {
  VAS1$Diff[VAS1$ID==i & VAS1$Day==1] = (VAS1$Sum[VAS1$Test==2 & VAS1$ID==i & VAS1$Day==1]- VAS1$Sum[VAS1$Test==1 & VAS1$ID==i & VAS1$Day==1])
}

sum(VAS1$Diff[VAS1$Condition=="HCL"])
sum(VAS1$Diff[VAS1$Condition=="LCL"])
mean(VAS1$Diff[VAS1$Condition=="HCL"])
mean(VAS1$Diff[VAS1$Condition=="LCL"])

#factors
VAS1$Day <- as.factor(VAS1$Day)
VAS1$Test <- as.factor(VAS1$Test)
VAS1$Condition <- as.factor(VAS1$Condition)
VAS1$ID <- as.factor(VAS1$ID)


one_way <- lm(Diff~Condition , data=VAS1)
library(emmeans)
emmeans1 <- emmeans(one_way, pairwise ~ Condition, adjust ="fdr", type = "response")
one_way_emm <- summary(emmeans1)$emmeans
one_way_plotf(VAS1, one_way_emm, "Diff") 

Anova(one_way, type='III')
summary(emmeans1)
emmeans1$contrasts


library("ggplot2")
emmeans1<-data.frame(emmeans1)
emmeans1<-emmeans1[-c(3),]
ggplot(emmeans1, aes(Condition, emmean)) +        # ggplot2 plot with confidence intervals
  geom_point() +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL))


# summarize 
## data table
library(data.table)
library(dplyr)
Data_dt <- as.data.table(VAS1)
Data_sum <- Data_dt[,.(meanResp=mean(Diff)), by = .(Condition, ID)]
my_sum <- Data_sum %>%
  group_by(Condition) %>%
  summarise(
    n = n(), 
    mean = mean(meanResp),
    sd = sd(meanResp)
  ) %>%
  mutate( se = sd/sqrt(n)) %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
print(my_sum)
## plot 
library(ggplot2)
library(ARTool)
library(MuMIn)
### using standard error
ggplot(my_sum) + 
  geom_bar( aes(x=Condition, y=mean), stat="identity", fill=c("black", "lightgrey"), alpha=0.5) + 
  geom_errorbar( aes(x=Condition, ymin=mean-se, ymax=mean+se), width=0.4, colour="white", alpha=0.9, size=1.5) +
  ggtitle("Experiment 1: Overall difference VAS1-f - using standard error")
### using confidence interval
ggplot(my_sum) +
  geom_bar( aes(x=Condition, y=mean), stat="identity", fill=c("black", "lightgrey"), alpha=0.5) +
  geom_errorbar( aes(x=Condition, ymin=mean-ic, ymax=mean+ic), width=0.4, colour="white", alpha=0.9, size=1.5) +
  ggtitle("Experiment 1: Overall Overall difference VAS1-f - using confidence interval")


# one sample t-tests
library(effsize)
VAS11 <- VAS11[VAS11$Condition == "DLPFC",] 
cohen.d(VAS1$Diff, f = NA, paired = TRUE, mu = 0.5)

```

```{r}
######### VAS-f DAY 2 ############
#Dataframe from day 2
VAS2 <- VAS[!(VAS$Day==1),]


#each time 13 questions, with answers on a scale of 0-9 (Response)
# if Question.key contains 'quantised' then it is on 1-10 
VAS2 <-VAS2[(grepl("quantised", VAS2$Question.Key)),]
VAS2 = subset(VAS2, select = -c(Question.Key, Local.Date, Participant.Private.ID, Task.Name))

# take sum of the scale per participant, per day/test. 
for (i in 1:97) {
  VAS2$Sum[VAS2$ID==i & VAS2$Test==1 ]= sum (VAS2$Response[VAS2$ID==i & VAS2$Test==1])
  VAS2$Sum[VAS2$ID==i & VAS2$Test==2 ]= sum (VAS2$Response[VAS2$ID==i & VAS2$Test==2])
}

# check if conditions are equal
length(VAS2$Sum[VAS2$Test==1 & VAS2$Day ==2 & VAS2$ID==1])
length(VAS2$Sum[VAS2$Test==2 & VAS2$Day ==2 & VAS2$ID==1])

# correcting for baseline: VAS2C$Diff as VAS2 op test 2 - test 1 per dag
for (i in 1:97) {
  VAS2$Diff[VAS2$ID==i] = (VAS2$Sum[VAS2$Test==2 & VAS2$ID==i]- VAS2$Sum[VAS2$Test==1 & VAS2$ID==i])
}

sum(VAS2$Diff[VAS2$Condition=="HCL"])
sum(VAS2$Diff[VAS2$Condition=="LCL"])
mean(VAS2$Diff[VAS2$Condition=="HCL"])
mean(VAS2$Diff[VAS2$Condition=="LCL"])

#factors
VAS2$Day <- as.factor(VAS2$Day)
VAS2$Test <- as.factor(VAS2$Test)
VAS2$Condition <- as.factor(VAS2$Condition)
VAS2$ID <- as.factor(VAS2$ID)


one_way <- lm(Diff~Condition , data=VAS2)
library(emmeans)
emmeans1 <- emmeans(one_way, pairwise ~ Condition, adjust ="fdr", type = "response")
one_way_emm <- summary(emmeans1)$emmeans
one_way_plotf(VAS2, one_way_emm, "Diff") 

Anova(one_way, type='III')
summary(emmeans1)
emmeans1$contrasts


library("ggplot2")
emmeans1<-data.frame(emmeans1)
emmeans1<-emmeans1[-c(3),]
ggplot(emmeans1, aes(Condition, emmean)) +        # ggplot2 plot with confidence intervals
  geom_point() +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL))


# summarize 
## data table
library(data.table)
library(dplyr)
Data_dt <- as.data.table(VAS2)
Data_sum <- Data_dt[,.(meanResp=mean(Diff)), by = .(Condition, ID)]
my_sum <- Data_sum %>%
  group_by(Condition) %>%
  summarise(
    n = n(), 
    mean = mean(meanResp),
    sd = sd(meanResp)
  ) %>%
  mutate( se = sd/sqrt(n)) %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
print(my_sum)
## plot 
library(ggplot2)µ
library(MuMIn)
### using standard error
ggplot(my_sum) + 
  geom_bar( aes(x=Condition, y=mean), stat="identity", fill=c("black", "lightgrey"), alpha=0.5) + 
  geom_errorbar( aes(x=Condition, ymin=mean-se, ymax=mean+se), width=0.4, colour="white", alpha=0.9, size=1.5) +
  ggtitle("Experiment 1: Overall difference VAS2-f - using standard error")
### using confidence interval
ggplot(my_sum) +
  geom_bar( aes(x=Condition, y=mean), stat="identity", fill=c("black", "lightgrey"), alpha=0.5) +
  geom_errorbar( aes(x=Condition, ymin=mean-ic, ymax=mean+ic), width=0.4, colour="white", alpha=0.9, size=1.5) +
  ggtitle("Experiment 1: Overall Overall difference VAS2-f - using confidence interval")


# one sample t-tests
library(effsize)
VAS21 <- VAS21[VAS21$Condition == "DLPFC",] 
cohen.d(VAS2$Diff, f = NA, paired = TRUE, mu = 0.5)



```

```{r}

#### VAS-f BOTH DAYS ######

#Dataframe from day 1
VAS = subset(VAS, select = -c(Local.Date, Participant.Private.ID, Task.Name))

# take means
#each time 13 questions, with answers on a scale of 0-9 (Response)
# if Question.key contains 'quantised' then it is on 1-10 
VAS <-VAS[(grepl("quantised", VAS$Question.Key)),]

# take sum of the scale per participant, per day/test. 
for (i in 1:97) {
  VAS$Sum[VAS$ID==i & VAS$Test==1 & VAS$Day==1]= sum (VAS$Response[VAS$ID==i & VAS$Test==1 & VAS$Day==1])
  VAS$Sum[VAS$ID==i & VAS$Test==2 & VAS$Day==1]= sum (VAS$Response[VAS$ID==i & VAS$Test==2 & VAS$Day==1])
  VAS$Sum[VAS$ID==i & VAS$Test==1 & VAS$Day==2]= sum (VAS$Response[VAS$ID==i & VAS$Test==1 & VAS$Day==2])
  VAS$Sum[VAS$ID==i & VAS$Test==2 & VAS$Day==2]= sum (VAS$Response[VAS$ID==i & VAS$Test==2 & VAS$Day==2])
}

# check if conditions are equal
length(VAS$Sum[VAS$Test==1 & VAS$Day ==1 & VAS$ID==1])
length(VAS$Sum[VAS$Test==2 & VAS$Day ==1 & VAS$ID==1])
length(VAS$Sum[VAS$Test==1 & VAS$Day ==2 & VAS$ID==1])
length(VAS$Sum[VAS$Test==2 & VAS$Day ==2 & VAS$ID==1])

# correcting for baseline: VASC$Diff as VAS op test 2 - test 1 per dag
for (i in 1:97) {
  VAS$Diff[VAS$ID==i & VAS$Day==1] = (VAS$Sum[VAS$Test==2 & VAS$ID==i & VAS$Day==1]- VAS$Sum[VAS$Test==1 & VAS$ID==i & VAS$Day==1])
  VAS$Diff[VAS$ID==i & VAS$Day==2] = (VAS$Sum[VAS$Test==2 & VAS$ID==i & VAS$Day==2]- VAS$Sum[VAS$Test==1 & VAS$ID==i & VAS$Day==2])
}

sum(VAS$Diff[VAS$Condition=="HCL"])
sum(VAS$Diff[VAS$Condition=="LCL"])
mean(VAS$Diff[VAS$Condition=="HCL"])
mean(VAS$Diff[VAS$Condition=="LCL"])

#factors
VAS$Day <- as.factor(VAS$Day)
VAS$Test <- as.factor(VAS$Test)
VAS$Condition <- as.factor(VAS$Condition)
VAS$ID <- as.factor(VAS$ID)


two_way <-lm(Diff~Condition * Day, data=VAS)
emmeans2 <- emmeans(two_way, pairwise ~ Condition * Day, adjust ="fdr", type = "response")
two_way_emm <- summary(emmeans2)$emmeans
two_way_plotf(VAS, two_way_emm, "Diff")

Anova(two_way, type='III')
summary(emmeans2)
emmeans2$contrasts


```

```{r}

#### TEST- RETEST RELIABILITY ######



```