---
title: "VAS_ANALYSIS"
author: "Sofie Raeymakers"
date: "5/3/2022"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls()) # Clear environment
cat("\014") # Clear console
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning = FALSE}
##### Set environment #####

library(tidyverse)
library(effects)
library(emmeans)
library(data.table)
library(dplyr)
library(ggplot2)
library(MuMIn)
library(effsize)
library(reshape2)
library(cowplot)
library(car)
library(ggpubr)
library(lme4)

# Get and declare functions
#Set working directory to the folder in which all CSV files are located

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
source("C:/Users/ASUSTeK/OneDrive/Documenten/Github/Short_TLoadDBack/functions.R") # This is a file in the same directory where you can stash your functions so you can save them there and have them together

Dir = "C:/Users/ASUSTeK/OneDrive/Documenten/Github/Short_TLoadDBack/Data/"
setwd(Dir)

#Download VAS-f data
VAS <- read.csv(paste0(Dir, "VAS.csv"), header = TRUE, sep = )
```

```{r}

# we want to see if there is a diff between VAS before and after TloadDback
#subjective measure of fatigue, on scale of 1-10
#we calculate a difference score
#plot, look at scores visually

# do same statistics as what Borrogan did


# calculate Diff
VAS = subset(VAS, select = -c(Local.Date, Participant.Private.ID, Task.Name))
VAS <-VAS[(grepl("quantised", VAS$Question.Key)),]

# take sum of the scale per participant, per day/test. 
for (i in 1:97) {
  VAS$Sum[VAS$ID==i & VAS$Test==1 & VAS$Day==1]= sum (VAS$Response[VAS$ID==i & VAS$Test==1 & VAS$Day==1])
  VAS$Sum[VAS$ID==i & VAS$Test==2 & VAS$Day==1]= sum (VAS$Response[VAS$ID==i & VAS$Test==2 & VAS$Day==1])
  VAS$Sum[VAS$ID==i & VAS$Test==1 & VAS$Day==2]= sum (VAS$Response[VAS$ID==i & VAS$Test==1 & VAS$Day==2])
  VAS$Sum[VAS$ID==i & VAS$Test==2 & VAS$Day==2]= sum (VAS$Response[VAS$ID==i & VAS$Test==2 & VAS$Day==2])
}

# check if conditions are equal
length(VAS$Sum[VAS$Test==1 & VAS$Day ==1 & VAS$ID==1])
length(VAS$Sum[VAS$Test==2 & VAS$Day ==1 & VAS$ID==1])
length(VAS$Sum[VAS$Test==1 & VAS$Day ==2 & VAS$ID==1])
length(VAS$Sum[VAS$Test==2 & VAS$Day ==2 & VAS$ID==1])

#make dataframe with 1 measure per condition
VAS<- VAS[VAS$Question.Key=='0-quantised',]

# difference score, devide by baseline (pre TloadBack) as a function of group (Day/condition): (2-1)/1
for (i in 1:97) {
  VAS$Diff[VAS$ID==i & VAS$Day==1] = 
    ((VAS$Sum[VAS$Test==2 & VAS$ID==i & VAS$Day==1]- VAS$Sum[VAS$Test==1 & VAS$ID==i & VAS$Day==1])/VAS$Sum[VAS$Test==1 & VAS$ID==i & VAS$Day==1])
  VAS$Diff[VAS$ID==i & VAS$Day==2] = 
    ((VAS$Sum[VAS$Test==2 & VAS$ID==i & VAS$Day==1]- VAS$Sum[VAS$Test==1 & VAS$ID==i & VAS$Day==2])/VAS$Sum[VAS$Test==1 & VAS$ID==i & VAS$Day==2])
}

#summary data
sum <- group_by(VAS, Condition, Day) %>%
  summarise(
    count = n(),
    mean = mean(Diff, na.rm = TRUE),
    sd = sd(Diff, na.rm = TRUE)
  )
sum 

#factors
VAS$Day <- as.factor(VAS$Day)
VAS$Test <- as.factor(VAS$Test)
VAS$Condition <- as.factor(VAS$Condition)
VAS$ID <- as.factor(VAS$ID)

# check for significant outliers: 
outliers <- boxplot(VAS$Diff, plot=FALSE)$out
# VAS<- VAS[-which(VAS$Diff %in% outliers),]
# log transform data
# PVT$RT = log(PVT$MeanRT)
#visualise
d<-melt(data.frame(Diff=c(VAS$Diff))) # we melt to wide format
ggplot(d, aes(x = variable, y = value, fill=variable))+
  geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust =2)+
  coord_flip()+
  theme_cowplot()+
  geom_point(position=position_jitter(width=.15), size=2)+
  geom_boxplot(width= .10, outlier.shape = NA)+
  theme(legend.position="VAS")

# plot Diff per condition and day
formula <- lmer('Diff ~ Day * Condition + (1|ID)', data= VAS)
emmean_dataframe = as.data.frame(emmeans(formula, pairwise ~ Day | Condition , adjust ="fdr", type = "response"))

two_w <- lm(Diff~Condition * Day, data=VAS)
emmeans1<- emmeans(two_w, pairwise ~ Condition * Day, adjust ="fdr", type = "response")
emmean_dataframe <- summary(emmeans1)$emmeans
 
 ggplot(VAS, aes(x= Day, y = Diff))+
    geom_flat_violin(aes(fill=Condition),position = position_nudge(x =.2, y = 0), alpha=.5, adjust = 1.5, colour = NA)+
  geom_boxplot(aes(x = Day, y = Diff, fill = Condition), outlier.shape=NA, alpha= .45, width = .1, colour = "black") +
    geom_point(data= emmean_dataframe, aes(x =Day, y = emmean, fill=Condition), position= position_dodge(0.1), size=4)+
    theme(
      legend.key.size=unit(1.3, 'cm'),
      legend.text=element_text(size=13),
      plot.title = element_text(size=rel(2)),
      panel.border = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(colour = "black"),
      panel.grid.major.y = element_line( size=.1, color="#dedede" ),
      axis.text.x=element_text(size=rel(1.5)),
      axis.title.y=element_text(size=rel(1.4)),
      axis.title.x = element_blank())

#statistics : CHECK PAPER BORROGAN!!!
 Anova(two_w, type='III')
summary(emmeans1)

#normality
qqPlot(VAS$Diff)
VAS %>%
  group_by(Day) %>%
  shapiro_test(Diff) # if p bigger than 0.05, normal distribution
ggqqplot(VAS, 'Diff', facet.by='Day')

#statistics
res.aov2 <- aov(Diff ~ Condition, data= VAS)
summary(res.aov2)

res.aov1 <- anova()

########## VAS-f  DAY 1###########


library("ggplot2")
one_w <- lm(Diff~Condition , data=VAS)
emmeans1<- emmeans(one_w, pairwise ~ Condition, adjust ="fdr", type = "response")
emmeans1<-data.frame(emmeans1)
emmeans1<-emmeans1[-c(3),]
ggplot(emmeans1, aes(Condition, emmean)) +        # ggplot2 plot with confidence intervals
  geom_point() +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL))


# summarize 
## data table
Data_dt <- as.data.table(VAS)
Data_sum <- Data_dt[,.(meanResp=mean(Diff)), by = .(Condition, ID)]
my_sum <- Data_sum %>%
  group_by(Condition) %>%
  summarise(
    n = n(), 
    mean = mean(meanResp),
    sd = sd(meanResp)
  ) %>%
  mutate( se = sd/sqrt(n)) %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
print(my_sum)
## plot 
### using standard error
ggplot(my_sum) + 
  geom_bar( aes(x=Condition, y=mean), stat="identity", fill=c("black", "lightgrey"), alpha=0.5) + 
  geom_errorbar( aes(x=Condition, ymin=mean-se, ymax=mean+se), width=0.4, colour="white", alpha=0.9, size=1.5) +
  ggtitle("Experiment 1: Overall difference VAS-f - using standard error")
### using confidence interval
ggplot(my_sum) +
  geom_bar( aes(x=Condition, y=mean), stat="identity", fill=c("black", "lightgrey"), alpha=0.5) +
  geom_errorbar( aes(x=Condition, ymin=mean-ic, ymax=mean+ic), width=0.4, colour="white", alpha=0.9, size=1.5) +
  ggtitle("Experiment 1: Overall Overall difference VAS-f - using confidence interval")


# one sample t-tests
library(effsize)
VAS11 <- VAS11[VAS11$Condition == "DLPFC",] 
cohen.d(VAS1$Diff, f = NA, paired = TRUE, mu = 0.5)

```

```{r}
######### VAS-f DAY 2 ############
#Dataframe from day 2
VAS2 <- VAS[!(VAS$Day==1),]


#each time 13 questions, with answers on a scale of 0-9 (Response)
# if Question.key contains 'quantised' then it is on 1-10 
VAS2 <-VAS2[(grepl("quantised", VAS2$Question.Key)),]
VAS2 = subset(VAS2, select = -c(Question.Key, Local.Date, Participant.Private.ID, Task.Name))

# take sum of the scale per participant, per day/test. 
for (i in 1:97) {
  VAS2$Sum[VAS2$ID==i & VAS2$Test==1 ]= sum (VAS2$Response[VAS2$ID==i & VAS2$Test==1])
  VAS2$Sum[VAS2$ID==i & VAS2$Test==2 ]= sum (VAS2$Response[VAS2$ID==i & VAS2$Test==2])
}

# check if conditions are equal
length(VAS2$Sum[VAS2$Test==1 & VAS2$Day ==2 & VAS2$ID==1])
length(VAS2$Sum[VAS2$Test==2 & VAS2$Day ==2 & VAS2$ID==1])

#make dataframe with 1 measure per condition
VAS2<- VAS2[VAS$Question.Key=='0-quantised',]

# correcting for baseline: VAS2C$Diff as VAS2 op test 2 - test 1 per dag
for (i in 1:97) {
  VAS2$Diff[VAS2$ID==i] = (VAS2$Sum[VAS2$Test==2 & VAS2$ID==i]- VAS2$Sum[VAS2$Test==1 & VAS2$ID==i])
}

sum(VAS2$Diff[VAS2$Condition=="HCL"])
sum(VAS2$Diff[VAS2$Condition=="LCL"])
mean(VAS2$Diff[VAS2$Condition=="HCL"])
mean(VAS2$Diff[VAS2$Condition=="LCL"])

#factors
VAS2$Day <- as.factor(VAS2$Day)
VAS2$Test <- as.factor(VAS2$Test)
VAS2$Condition <- as.factor(VAS2$Condition)
VAS2$ID <- as.factor(VAS2$ID)


one_way <- lm(Diff~Condition , data=VAS2)
emmeans1 <- emmeans(one_way, pairwise ~ Condition, adjust ="fdr", type = "response")
one_way_emm <- summary(emmeans1)$emmeans
one_way_plotf(VAS2, one_way_emm, "Diff") 

Anova(one_way, type='III')
summary(emmeans1)
emmeans1$contrasts


emmeans1<-data.frame(emmeans1)
emmeans1<-emmeans1[-c(3),]
ggplot(emmeans1, aes(Condition, emmean)) +        # ggplot2 plot with confidence intervals
  geom_point() +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL))


# summarize 
## data table
Data_dt <- as.data.table(VAS2)
Data_sum <- Data_dt[,.(meanResp=mean(Diff)), by = .(Condition, ID)]
my_sum <- Data_sum %>%
  group_by(Condition) %>%
  summarise(
    n = n(), 
    mean = mean(meanResp),
    sd = sd(meanResp)
  ) %>%
  mutate( se = sd/sqrt(n)) %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
print(my_sum)
## plot 
### using standard error
ggplot(my_sum) + 
  geom_bar( aes(x=Condition, y=mean), stat="identity", fill=c("black", "lightgrey"), alpha=0.5) + 
  geom_errorbar( aes(x=Condition, ymin=mean-se, ymax=mean+se), width=0.4, colour="white", alpha=0.9, size=1.5) +
  ggtitle("Experiment 1: Overall difference VAS2-f - using standard error")
### using confidence interval
ggplot(my_sum) +
  geom_bar( aes(x=Condition, y=mean), stat="identity", fill=c("black", "lightgrey"), alpha=0.5) +
  geom_errorbar( aes(x=Condition, ymin=mean-ic, ymax=mean+ic), width=0.4, colour="white", alpha=0.9, size=1.5) +
  ggtitle("Experiment 1: Overall Overall difference VAS2-f - using confidence interval")



```